pipeline {
agent any
    tools {
        maven 'Maven'
    }
     environment {
     VERSION = 'latest'
    }
    stages {
        stage('Preparation') {
           steps {
               sh 'echo Jenkins job: $JOB_NAME number: $BUILD_NUMBER has started...'
           }
        }
        stage('Code Quality') {
           steps {
               sh 'echo check sonar/quality tools'
           }
        }
        stage('Compile') {
           steps {
               sh 'mvn -f mypipe/pom.xml compile'
           }
        }
        stage('Unit Tests') {
           steps {
               sh 'mvn -f mypipe/pom.xml test'
           }
        }
        stage('Integration Test') {
           steps {
               sh 'mvn -f mypipe/pom.xml verify -DskipUnitTests'
           }
        }
        stage('Upload Image') {
           steps {
               script {
                   if (env.BRANCH_NAME == 'development') {
	        	  	 sh 'echo development registry pushing'
	        	 	}
				   if (env.BRANCH_NAME == 'master') {
	               	 sh 'echo docker url: $REGISTRY and version: $VERSION'				   	
	               	 sh 'echo master registry pushing'
	        	 }
               }
           }
        }
        stage('Approve') {
            input {
                message "Can we continue?"
                ok "Yes, please."
                submitter "hgormus@innova.com.tr"
                parameters {
                    string(name: 'Message', defaultValue: 'FINISH', description: 'Caution !! This deletes POD(s) ?')
                }
            }
            steps {
                echo "Hello, You ${Message}, we are completing the deployment"
            }
        }
        stage('Delete Pod') {
           steps {
               sh 'echo remove image from Kubernetes'
           }
        }
    }
    post {
        always {
            junit 'mypipe/target/surefire-reports/*.xml'
        }
     }
}