pipeline {
    agent any
    tools {
        maven 'Maven'
    }
    environment {
        MY_HI= "HELLO"
    }
    
    stages {
        stage('Preparation') {
        	steps {
        		sh 'echo build informations: '
	       		sh ' echo ${currentBuild.fullDisplayName} ${env.JOB_NAME} #${env.BUILD_NUMBER} '
           		sh 'echo second $MY_HI'
	        }
        }
        stage('Compile') {
        steps {
        	script {
	            if (env.BRANCH_NAME == 'development') {
	        	   sh 'echo this is development branch second part'
		       	   sh 'mvn -f mypipe/pom.xml compile'                          
	        	 }
				if (env.BRANCH_NAME == 'master') {
	               sh 'echo this is master branch second part'
		           sh 'mvn -f mypipe/pom.xml compile'                       
	        	 }
	        }

        	}
        }
       stage('Test') {
        	steps {
	            sh 'mvn -f mypipe/pom.xml test'
	        }
        }
        }
        
       post {
        always {
            junit 'mypipe/target/surefire-reports/*.xml'
        }
    }
        
        
        
            /*
    	 stage('Example') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
                submitter "alice,bob"
                parameters {
                    string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                }
            }
            steps {
                echo "Hello, ${PERSON}, nice to meet you."
            }
        }
        */
}