pipeline {
    agent any
    tools {
        maven 'Maven'
    }
    environment {
        MY_HI= "HELLO"
    }
    
    stages {
        stage('Preparation') {
        	steps {
	       		sh 'echo Hi its me'
           		sh 'echo second $MY_HI'
	        }
        }
        stage('Compile') {
        	if (env.BRANCH_NAME == 'development')
        		echo 'this is development branch'
        	else 
        		echo 'this is master branch'
        	when {
	            branch 'development'
	        }
        	steps {
	            sh 'mvn -f mypipe/pom.xml compile'
	        }
        }
       stage('Test') {
        	steps {
	            sh 'mvn -f mypipe/pom.xml test'
	        }
        }
        
        
        
            /*
    	 stage('Example') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
                submitter "alice,bob"
                parameters {
                    string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                }
            }
            steps {
                echo "Hello, ${PERSON}, nice to meet you."
            }
        }
        */
    }
}